/*
# Study Groups, Group Members, and Leaderboard Profiles

1. Purpose
   Adds real, persistent study groups with access codes, group membership,
   and a leaderboard table that stores each user's profile (name, exam, XP,
   streak) so the leaderboard page can show real data instead of fake
   sample entries.

2. New Tables
   - study_groups: a group created by a user. Has name, description, icon,
     a unique 6-character access_code, creator_name, and timestamps.
   - group_members: join table linking a user (identified by their local
     profile name + email/phone) to a study group. Tracks joined_at.
   - leaderboard_profiles: one row per user who has studied. Stores name,
     initials, exam, xp, streak, total_minutes, tests_taken, best_score_pct,
     and last_active date. This is what the leaderboard page queries.

3. Security
   - RLS enabled on every table.
   - All policies use `TO anon, authenticated` with `USING (true)` /
     `WITH CHECK (true)` because this is a single-tenant app with no
     sign-in — the anon-key client must read and write its own data.
   - Anyone using the app can create groups, join groups with a valid
     access code, and read all groups/members/leaderboard entries.

4. Important Notes
   - access_code is generated by the frontend as a random 6-char
     alphanumeric string and stored here. Uniqueness is enforced by a
     UNIQUE constraint.
   - leaderboard_profiles are upserted by the app whenever the user's
     stats change (XP, streak, etc.). The "name" column acts as the
     key since there is no auth.
*/

CREATE TABLE IF NOT EXISTS study_groups (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  icon text NOT NULL DEFAULT '📚',
  access_code text NOT NULL UNIQUE,
  creator_name text NOT NULL DEFAULT 'Anonymous',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE study_groups ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_select_study_groups" ON study_groups;
CREATE POLICY "anon_select_study_groups" ON study_groups FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_study_groups" ON study_groups;
CREATE POLICY "anon_insert_study_groups" ON study_groups FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_study_groups" ON study_groups;
CREATE POLICY "anon_delete_study_groups" ON study_groups FOR DELETE
  TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS group_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id uuid NOT NULL REFERENCES study_groups(id) ON DELETE CASCADE,
  member_name text NOT NULL,
  member_email text NOT NULL DEFAULT '',
  member_phone text NOT NULL DEFAULT '',
  joined_at timestamptz DEFAULT now(),
  UNIQUE(group_id, member_email)
);

ALTER TABLE group_members ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_select_group_members" ON group_members;
CREATE POLICY "anon_select_group_members" ON group_members FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_group_members" ON group_members;
CREATE POLICY "anon_insert_group_members" ON group_members FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_group_members" ON group_members;
CREATE POLICY "anon_delete_group_members" ON group_members FOR DELETE
  TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS leaderboard_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  initials text NOT NULL DEFAULT '',
  exam text NOT NULL DEFAULT '',
  xp integer NOT NULL DEFAULT 0,
  streak integer NOT NULL DEFAULT 0,
  total_minutes integer NOT NULL DEFAULT 0,
  tests_taken integer NOT NULL DEFAULT 0,
  best_score_pct integer,
  last_active date DEFAULT CURRENT_DATE,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE leaderboard_profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_select_leaderboard" ON leaderboard_profiles;
CREATE POLICY "anon_select_leaderboard" ON leaderboard_profiles FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_leaderboard" ON leaderboard_profiles;
CREATE POLICY "anon_insert_leaderboard" ON leaderboard_profiles FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_leaderboard" ON leaderboard_profiles;
CREATE POLICY "anon_update_leaderboard" ON leaderboard_profiles FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_leaderboard" ON leaderboard_profiles;
CREATE POLICY "anon_delete_leaderboard" ON leaderboard_profiles FOR DELETE
  TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_group_members_group_id ON group_members(group_id);
CREATE INDEX IF NOT EXISTS idx_leaderboard_xp ON leaderboard_profiles(xp DESC);
